import { NotaFiscalProcesso } from './types';

export const INITIAL_NOTAS_FISCAIS: NotaFiscalProcesso[] = [
  {
    id: 'nf-004821',
    numeroNF: '000.048.210',
    serie: '1',
    chaveAcesso: '35260904821098000145550010000482101004821098',
    dataEmissao: '2026-09-17 08:30',
    dataEntradaFiscal: '2026-09-17 11:15',
    docaDesignada: 'Doca 03 - Pesados',
    fornecedor: {
      nome: 'Metalúrgica Tubos & Conexões do Brasil S.A.',
      cnpj: '04.821.098/0001-45',
      cidadeUf: 'Piracicaba / SP',
      email: 'faturamento@metalurgicatubos.com.br',
      telefone: '(19) 3456-7800',
    },
    transportadora: {
      nome: 'TransLogística Rodoviária Expressa Ltda.',
      cnpj: '12.345.678/0001-90',
      motorista: 'Cláudio Ferreira Lima',
      cpfMotorista: '***.452.988-**',
      placaVeiculo: 'BRA4E21',
      telefoneMotorista: '(19) 98765-4321',
    },
    valorTotalNF: 48950.00,
    status: 'LIBERADO_DESCARGA',
    itens: [
      {
        id: 'it-1',
        codigo: 'TUB-INOX-304-2POL',
        descricao: 'Tubo Inox 304 Schedule 40 2" Barra 6m',
        ncm: '73064000',
        cfop: '5101',
        unidade: 'BARRA',
        quantidadeFaturada: 60,
        quantidadeRecebida: 0,
        valorUnitario: 380.00,
        valorTotal: 22800.00,
        divergenciaTipo: 'NENHUMA',
        lote: 'LT-2026-09-A',
      },
      {
        id: 'it-2',
        codigo: 'VLV-ESF-INOX-2',
        descricao: 'Válvula Esfera Tripartida Passagem Plena Inox 2"',
        ncm: '84818095',
        cfop: '5101',
        unidade: 'UN',
        quantidadeFaturada: 25,
        quantidadeRecebida: 0,
        valorUnitario: 650.00,
        valorTotal: 16250.00,
        divergenciaTipo: 'NENHUMA',
        lote: 'VLV-8841',
      },
      {
        id: 'it-3',
        codigo: 'JNT-VED-PTFE-2',
        descricao: 'Junta de Vedação Espiralada Inox 304 com PTFE 2"',
        ncm: '84841000',
        cfop: '5101',
        unidade: 'PC',
        quantidadeFaturada: 100,
        quantidadeRecebida: 0,
        valorUnitario: 99.00,
        valorTotal: 9900.00,
        divergenciaTipo: 'NENHUMA',
      }
    ],
    historico: [
      {
        id: 'h-1',
        dataHora: '2026-09-17 11:15',
        etapa: '1. Entrada da NF - Recebimento Fiscal',
        acao: 'Entrada registrada e validada com sucesso via SEFAZ/Arquivei.',
        responsavel: 'Fernanda Rocha Silva',
        setor: 'Recebimento Fiscal',
        detalhes: 'Chave conferida, manifesto validado. Caminhão liberado para seguir à Doca 03 do Almoxarifado.',
      },
      {
        id: 'h-2',
        dataHora: '2026-09-17 11:16',
        etapa: '2. Liberação para Descarga',
        acao: 'Processo disponibilizado na fila do Almoxarifado (Eliminação da ficha de papel).',
        responsavel: 'Sistema Integrado (TI)',
        setor: 'Automação Central',
        detalhes: 'Notificação em tempo real enviada ao tablet/terminal do Almoxarifado central.',
      }
    ]
  },
  {
    id: 'nf-004755',
    numeroNF: '000.047.550',
    serie: '2',
    chaveAcesso: '35260933099882000188550020000475501004755088',
    dataEmissao: '2026-09-16 14:10',
    dataEntradaFiscal: '2026-09-17 09:00',
    docaDesignada: 'Doca 01 - Almoxarifado Geral',
    fornecedor: {
      nome: 'Indústria Química & Solventes Paulista Ltda.',
      cnpj: '33.099.882/0001-88',
      cidadeUf: 'Campinas / SP',
      email: 'contato@quimicapaulista.ind.br',
      telefone: '(19) 3789-2200',
    },
    transportadora: {
      nome: 'Expresso Cargas Rápidas S/A',
      cnpj: '99.888.777/0002-11',
      motorista: 'Rogério de Souza Mendes',
      cpfMotorista: '***.781.339-**',
      placaVeiculo: 'FGS9J80',
    },
    valorTotalNF: 26400.00,
    status: 'COM_DIVERGENCIA',
    itens: [
      {
        id: 'it-201',
        codigo: 'LUB-IND-SINT-20L',
        descricao: 'Óleo Lubrificante Sintético Industrial ISO VG 220 Balde 20L',
        ncm: '27101932',
        cfop: '5102',
        unidade: 'BALDE',
        quantidadeFaturada: 50,
        quantidadeRecebida: 42,
        valorUnitario: 380.00,
        valorTotal: 19000.00,
        divergenciaTipo: 'FALTA',
        divergenciaQtd: -8,
        observacaoItem: 'Falta física na conferência: entregues apenas 42 baldes (faltam 8 baldes do faturado).',
        lote: 'L-220-SEP26',
      },
      {
        id: 'it-202',
        codigo: 'DESG-IND-SOLV-5L',
        descricao: 'Desengraxante Industrial Biodegradável Galão 5L',
        ncm: '34029090',
        cfop: '5102',
        unidade: 'GL',
        quantidadeFaturada: 40,
        quantidadeRecebida: 37,
        valorUnitario: 185.00,
        valorTotal: 7400.00,
        divergenciaTipo: 'AVARIA',
        divergenciaQtd: -3,
        observacaoItem: '3 galões chegaram com embalagem rompida e vazamento no assoalho do caminhão (recusados no ato).',
        lote: 'DG-0914',
      }
    ],
    divergencia: {
      id: 'div-004755',
      dataRegistro: '2026-09-17 10:25',
      registradoPor: 'Marcos Vinícius Prado',
      matricula: 'ALM-0492',
      tipoGeral: 'MISTA',
      valorTotalDivergente: 3595.00,
      itensAfetados: [
        {
          codigo: 'LUB-IND-SINT-20L',
          descricao: 'Óleo Lubrificante Sintético Industrial ISO VG 220 Balde 20L',
          unidade: 'BALDE',
          faturado: 50,
          recebido: 42,
          diferenca: -8,
          valorUnitario: 380.00,
          valorDivergente: 3040.00,
          tipo: 'FALTA',
          observacao: 'Falta física no fardo lacrado. Constatado no ato do descarregamento na Doca 01.',
        },
        {
          codigo: 'DESG-IND-SOLV-5L',
          descricao: 'Desengraxante Industrial Biodegradável Galão 5L',
          unidade: 'GL',
          faturado: 40,
          recebido: 37,
          diferenca: -3,
          valorUnitario: 185.00,
          valorDivergente: 555.00,
          tipo: 'AVARIA',
          observacao: '3 galões com tampa fissurada e vazamento químico. Segregados para não contaminação.',
        }
      ],
      notificacoes: [
        {
          setor: 'Faturamento',
          emailDestino: 'faturamento@empresa.com.br',
          assunto: '[DIVERGÊNCIA DE RECEBIMENTO] NF 000.047.550 - Solicitação de NF de Devolução / Recusa Parcial',
          enviadoEm: '2026-09-17 10:26',
          providenciasSolicitadas: 'Emitir NF de Devolução Parcial no valor de R$ 3.595,00 (8 baldes por falta e 3 galões avariados recusados) conforme ressalva no DACTE/Canhoto.',
          statusTratativa: 'NF Devolução Solicitada',
        },
        {
          setor: 'Compras',
          emailDestino: 'compras.suprimentos@empresa.com.br',
          assunto: '[ALERTA SUPRIMENTOS] Falta e Avaria na Entrega - Fornecedor Quimica Paulista - NF 000.047.550',
          enviadoEm: '2026-09-17 10:26',
          providenciasSolicitadas: 'Contatar o fornecedor Indústria Química Paulista para cobrar reposição urgente do saldo pendente (8 baldes) e abertura de RNC.',
          statusTratativa: 'Em Análise',
        },
        {
          setor: 'Financeiro',
          emailDestino: 'contasapagar@empresa.com.br',
          assunto: '[BLOQUEIO / GLOSA DE TITULO] NF 000.047.550 - Glosa de R$ 3.595,00',
          enviadoEm: '2026-09-17 10:26',
          providenciasSolicitadas: 'Bloquear vencimento do boleto ou glosar R$ 3.595,00 do valor faturado original (R$ 26.400,00 -> Novo valor líquido aceito: R$ 22.805,00).',
          statusTratativa: 'Boleto Bloqueado',
        }
      ],
      observacoesGerais: 'Motorista assinou termo de ressalva no manifesto de carga. Fotos dos galões avariados anexadas ao dossiê da ocorrência.'
    },
    assinaturaAlmoxarifado: {
      responsavel: 'Marcos Vinícius Prado',
      cargo: 'Conferente Líder de Almoxarifado',
      matricula: 'ALM-0492',
      departamento: 'Almoxarifado',
      dataHora: '2026-09-17 10:25:18',
      hashAutenticacao: 'SHA256-A89E19F4B611C87D922E09B1A45F00C',
      rubricaBase64: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="160" height="60"><path d="M 10 40 Q 40 10, 80 35 T 150 25" stroke="%230f172a" stroke-width="2.5" fill="none"/></svg>',
      ipOrigem: '192.168.10.45 (Terminal Coletor Doca 01)',
    },
    historico: [
      {
        id: 'h-10',
        dataHora: '2026-09-17 09:00',
        etapa: '1. Entrada da NF - Recebimento Fiscal',
        acao: 'Entrada efetuada no sistema fiscal e liberado para descarga.',
        responsavel: 'Fernanda Rocha Silva',
        setor: 'Recebimento Fiscal',
      },
      {
        id: 'h-11',
        dataHora: '2026-09-17 09:30',
        etapa: '3. Descarga e Conferência - Almoxarifado',
        acao: 'Descarga iniciada na Doca 01 e conferência física detalhada.',
        responsavel: 'Marcos Vinícius Prado',
        setor: 'Almoxarifado',
      },
      {
        id: 'h-12',
        dataHora: '2026-09-17 10:25',
        etapa: 'Tratamento de Divergências',
        acao: 'Divergência registrada com assinatura eletrônica do Almoxarife.',
        responsavel: 'Marcos Vinícius Prado',
        setor: 'Almoxarifado',
        detalhes: 'Falta de 8 baldes e recusa de 3 galões avariados. Total divergente: R$ 3.595,00.',
      },
      {
        id: 'h-13',
        dataHora: '2026-09-17 10:26',
        etapa: 'Disparo Automático de E-mails',
        acao: 'Notificações geradas e enviadas para Faturamento, Compras e Financeiro.',
        responsavel: 'Sistema de Automação de Recebimento',
        setor: 'TI / Integração',
        detalhes: 'Disparo automático de e-mails com memorial descritivo da NF, itens e ações requeridas.',
      }
    ]
  },
  {
    id: 'nf-004712',
    numeroNF: '000.047.120',
    serie: '1',
    chaveAcesso: '35260901234567000199550010000471201004712033',
    dataEmissao: '2026-09-16 11:20',
    dataEntradaFiscal: '2026-09-17 08:10',
    docaDesignada: 'Doca 02 - Matérias-Primas',
    fornecedor: {
      nome: 'Aços & Laminados Especiais do Sul S.A.',
      cnpj: '01.234.567/0001-99',
      cidadeUf: 'Porto Alegre / RS',
      email: 'nf@acosdosul.com.br',
    },
    transportadora: {
      nome: 'Transportes Mercosul Rodoviário Ltda.',
      cnpj: '55.444.333/0001-22',
      motorista: 'Valter Siqueira Gomes',
      cpfMotorista: '***.209.110-**',
      placaVeiculo: 'RST3H44',
    },
    valorTotalNF: 38400.00,
    status: 'AGUARDANDO_FISCAL',
    itens: [
      {
        id: 'it-301',
        codigo: 'BOB-ACO-GALV-1.5',
        descricao: 'Bobina de Aço Galvanizado 1.5mm x 1200mm',
        ncm: '72104910',
        cfop: '6101',
        unidade: 'KG',
        quantidadeFaturada: 6000,
        quantidadeRecebida: 6000,
        valorUnitario: 6.40,
        valorTotal: 38400.00,
        divergenciaTipo: 'NENHUMA',
        lote: 'L-GALV-994',
      }
    ],
    assinaturaAlmoxarifado: {
      responsavel: 'Lucas Gabriel Pinheiro',
      cargo: 'Conferente Almoxarife',
      matricula: 'ALM-0310',
      departamento: 'Almoxarifado',
      dataHora: '2026-09-17 09:40:05',
      hashAutenticacao: 'SHA256-F14C890B38914B97EE11200CDA42199',
      rubricaBase64: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="160" height="60"><path d="M 15 35 Q 50 15, 90 40 T 145 20" stroke="%230f172a" stroke-width="2.5" fill="none"/></svg>',
      ipOrigem: '192.168.10.46 (Doca 02)',
    },
    historico: [
      {
        id: 'h-21',
        dataHora: '2026-09-17 08:10',
        etapa: '1. Entrada da NF - Recebimento Fiscal',
        acao: 'Entrada registrada e material liberado para descarga.',
        responsavel: 'Fernanda Rocha Silva',
        setor: 'Recebimento Fiscal',
      },
      {
        id: 'h-22',
        dataHora: '2026-09-17 09:40',
        etapa: '3. Descarga e Conferência - Almoxarifado',
        acao: 'Conferência física 100% conforme. Assinatura eletrônica realizada.',
        responsavel: 'Lucas Gabriel Pinheiro',
        setor: 'Almoxarifado',
        detalhes: 'Pesagem e pesagem líquida conferidas com o peso bruto da DANFE. Aguardando conclusão do Fiscal.',
      }
    ]
  },
  {
    id: 'nf-004680',
    numeroNF: '000.046.800',
    serie: '1',
    chaveAcesso: '35260977889900000177550010000468001004680099',
    dataEmissao: '2026-09-15 16:00',
    dataEntradaFiscal: '2026-09-16 10:00',
    docaDesignada: 'Doca 04 - Suprimentos e EPIs',
    fornecedor: {
      nome: 'Segurança & EPI Brasil Comércio e Indústria Ltda.',
      cnpj: '77.889.900/0001-77',
      cidadeUf: 'São Paulo / SP',
      email: 'pedidos@segurancaepibrasil.com.br',
    },
    transportadora: {
      nome: 'Rápido Encomendas Paulistas Eireli',
      cnpj: '44.333.222/0001-88',
      motorista: 'Antônio Carlos Batista',
      cpfMotorista: '***.889.201-**',
      placaVeiculo: 'GHK7721',
    },
    valorTotalNF: 15720.00,
    status: 'CONCLUIDO',
    itens: [
      {
        id: 'it-401',
        codigo: 'EPI-BOT-BICO-41',
        descricao: 'Botina de Segurança Nobuck com Bico Composite Nº 41 CA 42100',
        ncm: '64034000',
        cfop: '5102',
        unidade: 'PAR',
        quantidadeFaturada: 60,
        quantidadeRecebida: 60,
        valorUnitario: 145.00,
        valorTotal: 8700.00,
        divergenciaTipo: 'NENHUMA',
      },
      {
        id: 'it-402',
        codigo: 'EPI-LUV-NITRIL-G',
        descricao: 'Luva de Proteção Mecânica Banho Nitrílico Tamanho G',
        ncm: '61161000',
        cfop: '5102',
        unidade: 'PAR',
        quantidadeFaturada: 320,
        quantidadeRecebida: 320,
        valorUnitario: 12.50,
        valorTotal: 4000.00,
        divergenciaTipo: 'NENHUMA',
      },
      {
        id: 'it-403',
        codigo: 'EPI-OCUL-INCOLOR',
        descricao: 'Óculos de Segurança Antirrisco e Antiembaçante Incolor',
        ncm: '90049020',
        cfop: '5102',
        unidade: 'UN',
        quantidadeFaturada: 151,
        quantidadeRecebida: 151,
        valorUnitario: 20.00,
        valorTotal: 3020.00,
        divergenciaTipo: 'NENHUMA',
      }
    ],
    assinaturaAlmoxarifado: {
      responsavel: 'Lucas Gabriel Pinheiro',
      cargo: 'Conferente Almoxarife',
      matricula: 'ALM-0310',
      departamento: 'Almoxarifado',
      dataHora: '2026-09-16 11:30:12',
      hashAutenticacao: 'SHA256-8B291A77E90B01D784CFA098177B12C',
      rubricaBase64: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="160" height="60"><path d="M 15 35 Q 50 15, 90 40 T 145 20" stroke="%230f172a" stroke-width="2.5" fill="none"/></svg>',
      ipOrigem: '192.168.10.46 (Doca 04)',
    },
    assinaturaFiscal: {
      responsavel: 'Fernanda Rocha Silva',
      cargo: 'Analista de Recebimento Fiscal Sênior',
      matricula: 'FIS-0188',
      departamento: 'Recebimento Fiscal',
      dataHora: '2026-09-16 11:45:30',
      hashAutenticacao: 'SHA256-4D8832BA7C810E9931FCA902B890471',
      rubricaBase64: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="160" height="60"><path d="M 20 40 Q 60 10, 100 35 T 150 22" stroke="%230f172a" stroke-width="2.5" fill="none"/></svg>',
      ipOrigem: '192.168.10.12 (Posto Fiscal Entrada)',
    },
    canhotoDigital: {
      codigoCanhoto: 'CNH-2026-046800',
      dataHoraLiberacao: '2026-09-16 11:45:30',
      liberadoPorFiscal: 'Fernanda Rocha Silva (Matr. FIS-0188)',
      matriculaFiscal: 'FIS-0188',
      conferidoPorAlmoxarife: 'Lucas Gabriel Pinheiro (Matr. ALM-0310)',
      matriculaAlmoxarife: 'ALM-0310',
      motoristaRecebedor: 'Antônio Carlos Batista',
      placaVeiculo: 'GHK7721',
      autenticidadeHash: 'CNH-AUT-7890-ABCD-9912-2026',
      situacaoCanhoto: 'Liberado com Sucesso',
    },
    historico: [
      {
        id: 'h-31',
        dataHora: '2026-09-16 10:00',
        etapa: '1. Entrada da NF - Recebimento Fiscal',
        acao: 'Entrada registrada no sistema.',
        responsavel: 'Fernanda Rocha Silva',
        setor: 'Recebimento Fiscal',
      },
      {
        id: 'h-32',
        dataHora: '2026-09-16 11:30',
        etapa: '3. Descarga e Conferência - Almoxarifado',
        acao: 'Conferência 100% aprovada e assinado digitalmente.',
        responsavel: 'Lucas Gabriel Pinheiro',
        setor: 'Almoxarifado',
      },
      {
        id: 'h-33',
        dataHora: '2026-09-16 11:45',
        etapa: '4. Conclusão do Processo - Recebimento Fiscal',
        acao: 'Validação final aprovada, assinatura eletrônica e liberação de canhoto.',
        responsavel: 'Fernanda Rocha Silva',
        setor: 'Recebimento Fiscal',
        detalhes: 'Canhoto digital CNH-2026-046800 gerado e entregue ao motorista Antônio Carlos.',
      }
    ]
  }
];

export const TEMPLATES_NF_ENTRADA = [
  {
    nomeTemplate: 'Carga de Parafusos e Fixadores Industriais',
    fornecedor: 'Metalfix Parafusos & Fixadores Ltda.',
    cnpj: '18.992.334/0001-55',
    cidadeUf: 'Joinville / SC',
    transportadora: 'TransFix Sul Cargas',
    motorista: 'Edson Arantes Pereira',
    placa: 'SCJ8A90',
    doca: 'Doca 01 - Almoxarifado Geral',
    itens: [
      {
        codigo: 'PAR-SEXT-M12X50',
        descricao: 'Parafuso Sextavado M12 x 50mm Grau 8.8 Zincado',
        ncm: '73181500',
        cfop: '5101',
        unidade: 'CENTO',
        quantidadeFaturada: 25,
        valorUnitario: 145.00,
      },
      {
        codigo: 'POR-AUTOTRAV-M12',
        descricao: 'Porca Autotravante M12 com Anel de Nylon Zincada',
        ncm: '73181600',
        cfop: '5101',
        unidade: 'CENTO',
        quantidadeFaturada: 30,
        valorUnitario: 68.00,
      },
      {
        codigo: 'ARR-LISA-M12',
        descricao: 'Arruela Lisa M12 Aço Carbono Zincada',
        ncm: '73182200',
        cfop: '5101',
        unidade: 'CENTO',
        quantidadeFaturada: 50,
        valorUnitario: 32.00,
      }
    ]
  },
  {
    nomeTemplate: 'Carga de Rolamentos & Mancais de Precisão',
    fornecedor: 'Rolamax Rolamentos Industriais S.A.',
    cnpj: '61.442.110/0001-92',
    cidadeUf: 'São Bernardo do Campo / SP',
    transportadora: 'Expresso Paulistano de Cargas',
    motorista: 'Maurício Tavares Neves',
    placa: 'SPX5T12',
    doca: 'Doca 02 - Matérias-Primas',
    itens: [
      {
        codigo: 'ROL-ESF-6205-2RS',
        descricao: 'Rolamento Rígido de Esferas 6205-2RS Folga C3',
        ncm: '84821010',
        cfop: '5101',
        unidade: 'UN',
        quantidadeFaturada: 120,
        valorUnitario: 42.50,
      },
      {
        codigo: 'MAN-PEDESTAL-P205',
        descricao: 'Mancal Pedestal Ferro Fundido P205 para Eixo 25mm',
        ncm: '84832000',
        cfop: '5101',
        unidade: 'PC',
        quantidadeFaturada: 40,
        valorUnitario: 89.00,
      }
    ]
  }
];
